### ISSUE TITLE
Missing collaborator data for CHD7 - CHARGE syndrome 

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#56]
CHD7 - CHARGE syndrome was republished in Feb but doesn't look to have collaborator data for the display.  

https://search.clinicalgenome.org/kb/gene-validity/26ae5799-567b-431b-b981-3bc2f8635802--2018-08-22T20:16:33

**Comment by sgoehringer** [comment]
@tnavatar can you check into this... I looked at Neo4J data and I see three curations.  Two have similar but I'm unsure why the "wasInvalidatedBy" relationship isn't connected.  I see it for a older curation but the newer one (GCI.7) doesn't have it over to the (GCI.5)

date: 2018-08-22T16:00:00.000Z
gci_id: 26ae5799-567b-431b-b981-3bc2f8635802
iri: 26ae5799-567b-431b-b981-3bc2f8635802--2018-08-22T16:00:00
jsonMessageVersion: GCI.7
perm_id: 26ae5799-567b-431b-b981-3bc2f8635802--2018-08-22T16:00:00

date: 2018-08-22T20:16:33.685Z
gci_id: 26ae5799-567b-431b-b981-3bc2f8635802
iri: 26ae5799-567b-431b-b981-3bc2f8635802--2018-08-22T20:16:33
jsonMessageVersion: GCI.5
perm_id: 26ae5799-567b-431b-b981-3bc2f8635802--2018-08-22T20:16:33

**Comment by sgoehringer** [comment]
@tnavatar I spot checked a series of curations (a few hundred) and I didn't see a pattern where updates to curations didn't have the wasInvalidatedBy (though it was only spot checks).  I am curious what you find during your review of why the relationship wasn't connected. Once you report back it may shed enough light on to what other testing may be needed to continue audit/testing.

**Comment by tnavatar** [comment]
I think the issue here is that I'm only marking as invalidated if previous date < new date (am trying to avoid invalidating newer curations in case old data is reprocessed). In this case, the newer, desired curation actually has a timestamp older than the last, valid published one; for some reason the GCI is now sending this as midnight UTC, no matter when the curation was actually published.

I don't really want to change the import logic, since this would really screw things up if we reimport. We could do a one-off edit of the DB, but this would be fragile since reimporting would lose this info, but it might be the best thing we can do for now until Genegraph.

**Comment by sgoehringer** [comment]
@tnavatar I worked with the stakeholders and we concluded that simply revising the curation date from 8/22 to 8/23 would address this issue and also ensure that someone using the streaming service in the future wouldn't possibly have the same issue.

**Comment by sgoehringer** [comment]
Closing because the data change worked and the curation shows on the site.
